CREATE TABLE DirtyGirl.dbo.Address (
	AddressId INT NOT NULL PRIMARY KEY,
	Address1 VARCHAR(100) NOT NULL,
	Address2 VARCHAR(100) NULL,
	Locality VARCHAR(50) NOT NULL,
	RegionId INT NOT NULL FOREIGN KEY REFERENCES Region,
	PostalCode VARCHAR(20) NOT NULL
);

