Create Table DirtyWord
(
	WordID int not null identity(1,1) constraint pk_DirtyWord primary key,
	Word varchar(100)
)


insert into dirtyword (word) values ('ass')
insert into dirtyword (word) values ('asses')
insert into dirtyword (word) values ('asshole')
insert into dirtyword (word) values ('assholes')
insert into dirtyword (word) values ('bastard')
insert into dirtyword (word) values ('beaver')
insert into dirtyword (word) values ('beavers')
insert into dirtyword (word) values ('bitch')
insert into dirtyword (word) values ('bitches')
insert into dirtyword (word) values ('boobies')
insert into dirtyword (word) values ('boobs')
insert into dirtyword (word) values ('bullshit')
insert into dirtyword (word) values ('carpetmuncher')
insert into dirtyword (word) values ('cock')
insert into dirtyword (word) values ('cocks')
insert into dirtyword (word) values ('coochie')
insert into dirtyword (word) values ('cunt')
insert into dirtyword (word) values ('cunts')
insert into dirtyword (word) values ('dammit')
insert into dirtyword (word) values ('dick')
insert into dirtyword (word) values ('dickhead')
insert into dirtyword (word) values ('dickheads')
insert into dirtyword (word) values ('dickies')
insert into dirtyword (word) values ('dicky')
insert into dirtyword (word) values ('douche bag')
insert into dirtyword (word) values ('fuck')
insert into dirtyword (word) values ('fucker')
insert into dirtyword (word) values ('fuckers')
insert into dirtyword (word) values ('hoe')
insert into dirtyword (word) values ('hoes')
insert into dirtyword (word) values ('penis')
insert into dirtyword (word) values ('penises')
insert into dirtyword (word) values ('puss')
insert into dirtyword (word) values ('pussies')
insert into dirtyword (word) values ('pussy')
insert into dirtyword (word) values ('pussys')
insert into dirtyword (word) values ('puta')
insert into dirtyword (word) values ('putas')
insert into dirtyword (word) values ('shit')
insert into dirtyword (word) values ('shitty')
insert into dirtyword (word) values ('slut')
insert into dirtyword (word) values ('snatch')
insert into dirtyword (word) values ('snatches')
insert into dirtyword (word) values ('sonofabitch')
insert into dirtyword (word) values ('sonofabitches')
insert into dirtyword (word) values ('suck')
insert into dirtyword (word) values ('suckers')
insert into dirtyword (word) values ('sucks')
insert into dirtyword (word) values ('tit')
insert into dirtyword (word) values ('tits')
insert into dirtyword (word) values ('titties')
insert into dirtyword (word) values ('tittys')
insert into dirtyword (word) values ('vadge')
insert into dirtyword (word) values ('vadges')
insert into dirtyword (word) values ('vag')
insert into dirtyword (word) values ('vagina')
insert into dirtyword (word) values ('VJJ')
insert into dirtyword (word) values ('whore')
insert into dirtyword (word) values ('whores')